name: Upload release

on:
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up folder structure
        run: |
          dist_path=dist/BepInEx/plugins/CommunityTranslations
          mkdir -p $dist_path
          cp README.md $dist_path/README.md
          cp LICENSE $dist_path/LICENSE
          cp -r plugin_template $dist_path

      - name: Extract current version
        id: get-version
        run: |
          version=$(jq -r '.version' plugin_template/swinfo.json)
          echo "Version is $version"
          echo "version=$version" >> $GITHUB_ENV
          echo "artifact_name=CommunityTranslations-$version.zip" >> $GITHUB_ENV
          echo "upload_url=$(wget -qO- https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq '.[0].upload_url' | tr -d \")" >> $GITHUB_ENV

      - name: Build release zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release.zip dist/BepInEx

      - name: Publish release
        uses: shogo82148/actions-upload-release-asset@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: release.zip
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/zip